name: Deploy App1 to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            echo "==> Atualizando código"
            cd /home/senadev/apps/app1/src
            git fetch origin
            git reset --hard origin/main

            echo "==> Subindo container"
            cd /home/senadev/apps/app1
            docker compose up -d --build --remove-orphans

            echo "==> Containers:"
            docker ps